@"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "taskeenafifa934@gmail.com"
SENDER_PASSWORD = "rkzi jjpi yydy ldhc"
ADMIN_EMAILS = "taskeenafifa934@gmail.com"
"@ | Out-File -FilePath .streamlit\secrets.toml -Encoding UTF8